language: node_js
node_js:
  - "6"
after_success:
  - npm install codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=708d4c9e17f6e57c2f5f8bac05ab335846c06ac501af0624381a89217e627563 codeclimate-test-reporter < coverage/lcov.info
